### ISSUE TITLE
Add `v1` and `Common Node Api` rust bindings for the `test-suite`

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/filecoin-common-node-api#21]
We only have v0, at the moment, generated by `Forest`, we actually want:
- A FULL v1, generated by forest
- A Common Node API one, so that tests can be written against just the CNAPI

**Comment by LesnyRumcajs** [comment]
@elmattic was this closed via https://github.com/ChainSafe/filecoin-common-node-api/pull/37?
