### ISSUE TITLE
Validate method calls in-flight

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/filecoin-common-node-api#23]
We should add some of the functionality of `tool openrpc validate` into the test suite itself. 

Should probably do this after the test is run, or dump logs and allow the user to run as a separate step.

- [x] #52
- [ ] #53
- [ ] #54
- [ ] #55
- [ ] #36
- [ ] #56
- [ ] #58

**Comment by LesnyRumcajs** [comment]
Guillaume: (probably) everything from API compare to here

**Comment by ansermino** [comment]
@elmattic As discussed, we should perhaps focus on the openrpc validation exclusively, so that we can get this out the door. 

Would it make sense to reformulate this issue, or throw it out and start again?

**Comment by elmattic** [comment]
Indeed, let's close this. Openrpc spec validation is now happening in #57.
