### ISSUE TITLE
Add ci to repo

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/filecoin-common-node-api#32]
current rust `#[test]`s are for docs etc, no e2e tests yet

**Comment by LesnyRumcajs** [comment]
@elmattic Could you please provide a description with tasks to do within this issue? I imagine we should start with a smallest CI possible, then iterate from there.

**Comment by elmattic** [comment]
The kind of tests we want to add to the CI are basically those covered by `cargo test`:

`cargo test --manifest-path ./rust/Cargo.toml`

**Comment by elmattic** [comment]
e2e tests would be the ones run by the `test-suite` tool and/or `openrpc validate` of a capture.

**Comment by LesnyRumcajs** [comment]
@ansermino @elmattic given https://github.com/ChainSafe/filecoin-common-node-api/pull/42 and https://github.com/ChainSafe/filecoin-common-node-api/pull/40, do we consider this issue closed?

**Comment by elmattic** [comment]
I think so.
