### ISSUE TITLE
Replace reference to rust types

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/filecoin-common-node-api#4]
<img width="393" alt="Screenshot 2024-06-26 at 4 08 14 AM" src="https://github.com/ChainSafe/filecoin-common-node-api/assets/14164624/c5d1bf00-ba8f-45ef-b8ba-167ecfa5643b">

**Comment by aatifsyed** [comment]
https://github.com/ChainSafe/forest/pull/4572
