### ISSUE TITLE
Add links to OpenRPC Playground

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/filecoin-common-node-api#5]
We should link to the OpenRPC playground as a means to explore the spec. 

Currently its doesn't seem possible to link to the playground and have the spec auto-loaded. We may want to consider contributing to the playground to make linking such as this possible.

**Comment by aatifsyed** [comment]
> Currently its doesn't seem possible to link to the playground and have the spec auto-loaded

It is. I've added this to #1
