### ISSUE TITLE
Invalid OpenRPC Version

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/filecoin-common-node-api#6]
The playground complains about the OpenRPC version. We need to investigate if this is an issue with the playground, or with the version being specified.

<img width="774" alt="Screenshot 2024-06-26 at 6 46 21 AM" src="https://github.com/ChainSafe/filecoin-common-node-api/assets/14164624/8bd7ec7a-ec16-4755-8db3-b2dcd18189d1">

**Comment by aatifsyed** [comment]
This is a bug in the playground, probably resolved by https://github.com/open-rpc/playground/pull/605, I believe you're going to get in touch with the contributor involved
